




CREATE TABLE Office (
 primaryKey UUID NOT NULL,
 Address VARCHAR(255) NULL,
 Floor INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ComputerPart (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 SerialNumber VARCHAR(255) NULL,
 SizeOrCapacity VARCHAR(255) NULL,
 ComputerPartType_m0 UUID NOT NULL,
 Computer_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Person (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 Phone VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Computer (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 Office_m0 UUID NULL,
 Owner_m0 UUID NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ComputerPartType (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE ComputerPart ADD CONSTRAINT FK83e7df6437f30cbd0bf32d83547245f5460ec0b8 FOREIGN KEY (ComputerPartType_m0) REFERENCES ComputerPartType; 
CREATE INDEX Index83e7df6437f30cbd0bf32d83547245f5460ec0b8 on ComputerPart (ComputerPartType_m0); 

 ALTER TABLE ComputerPart ADD CONSTRAINT FKc92550d781b5b692953cf0089032b6755b35d48d FOREIGN KEY (Computer_m0) REFERENCES Computer; 
CREATE INDEX Indexc92550d781b5b692953cf0089032b6755b35d48d on ComputerPart (Computer_m0); 

 ALTER TABLE Computer ADD CONSTRAINT FK159bcdb5818d160bd33ea2faf7dd706dee1a3608 FOREIGN KEY (Office_m0) REFERENCES Office; 
CREATE INDEX Index159bcdb5818d160bd33ea2faf7dd706dee1a3608 on Computer (Office_m0); 

 ALTER TABLE Computer ADD CONSTRAINT FKca88de0202e56048ea338cd4d41ba177e34b60de FOREIGN KEY (Owner_m0) REFERENCES Person; 
CREATE INDEX Indexca88de0202e56048ea338cd4d41ba177e34b60de on Computer (Owner_m0); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

