//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Computers
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Computer part type.
    /// </summary>
    //  *** Start programmer edit section *** (ComputerPartType CustomAttributes)

    //  *** End programmer edit section *** (ComputerPartType CustomAttributes)
    [AutoAltered()]
    [Caption("Computer part type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ComputerPartTypeE", new string[] {
            "Name as \'Name\'"})]
    [View("ComputerPartTypeL", new string[] {
            "Name as \'Name\'"})]
    public class ComputerPartType : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        //  *** Start programmer edit section *** (ComputerPartType CustomMembers)

        //  *** End programmer edit section *** (ComputerPartType CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (ComputerPartType.Name CustomAttributes)

        //  *** End programmer edit section *** (ComputerPartType.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (ComputerPartType.Name Get start)

                //  *** End programmer edit section *** (ComputerPartType.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (ComputerPartType.Name Get end)

                //  *** End programmer edit section *** (ComputerPartType.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ComputerPartType.Name Set start)

                //  *** End programmer edit section *** (ComputerPartType.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (ComputerPartType.Name Set end)

                //  *** End programmer edit section *** (ComputerPartType.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ComputerPartTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ComputerPartTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ComputerPartTypeE", typeof(IIS.Computers.ComputerPartType));
                }
            }
            
            /// <summary>
            /// "ComputerPartTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ComputerPartTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ComputerPartTypeL", typeof(IIS.Computers.ComputerPartType));
                }
            }
        }
    }
}
