//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Computers
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Computer.
    /// </summary>
    //  *** Start programmer edit section *** (Computer CustomAttributes)

    //  *** End programmer edit section *** (Computer CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ComputerE", new string[] {
            "Name as \'Name\'",
            "Office as \'Office\'",
            "Office.Address as \'Address\'",
            "Owner as \'Owner\'",
            "Owner.Name as \'Name\'"}, Hidden=new string[] {
            "Office.Address",
            "Owner.Name"})]
    [AssociatedDetailViewAttribute("ComputerE", "Parts", "ComputerPartE", true, "", "Parts", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ComputerE", "Office", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Address")]
    [MasterViewDefineAttribute("ComputerE", "Owner", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("ComputerL", new string[] {
            "Name as \'Name\'",
            "Office.Address as \'Address\'",
            "Owner.Name as \'Name\'"})]
    public class Computer : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.Computers.Office fOffice;
        
        private IIS.Computers.Person fOwner;
        
        private IIS.Computers.DetailArrayOfComputerPart fParts;
        
        //  *** Start programmer edit section *** (Computer CustomMembers)

        //  *** End programmer edit section *** (Computer CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Computer.Name CustomAttributes)

        //  *** End programmer edit section *** (Computer.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Computer.Name Get start)

                //  *** End programmer edit section *** (Computer.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Computer.Name Get end)

                //  *** End programmer edit section *** (Computer.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Computer.Name Set start)

                //  *** End programmer edit section *** (Computer.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Computer.Name Set end)

                //  *** End programmer edit section *** (Computer.Name Set end)
            }
        }
        
        /// <summary>
        /// Computer.
        /// </summary>
        //  *** Start programmer edit section *** (Computer.Office CustomAttributes)

        //  *** End programmer edit section *** (Computer.Office CustomAttributes)
        public virtual IIS.Computers.Office Office
        {
            get
            {
                //  *** Start programmer edit section *** (Computer.Office Get start)

                //  *** End programmer edit section *** (Computer.Office Get start)
                IIS.Computers.Office result = this.fOffice;
                //  *** Start programmer edit section *** (Computer.Office Get end)

                //  *** End programmer edit section *** (Computer.Office Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Computer.Office Set start)

                //  *** End programmer edit section *** (Computer.Office Set start)
                this.fOffice = value;
                //  *** Start programmer edit section *** (Computer.Office Set end)

                //  *** End programmer edit section *** (Computer.Office Set end)
            }
        }
        
        /// <summary>
        /// Computer.
        /// </summary>
        //  *** Start programmer edit section *** (Computer.Owner CustomAttributes)

        //  *** End programmer edit section *** (Computer.Owner CustomAttributes)
        public virtual IIS.Computers.Person Owner
        {
            get
            {
                //  *** Start programmer edit section *** (Computer.Owner Get start)

                //  *** End programmer edit section *** (Computer.Owner Get start)
                IIS.Computers.Person result = this.fOwner;
                //  *** Start programmer edit section *** (Computer.Owner Get end)

                //  *** End programmer edit section *** (Computer.Owner Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Computer.Owner Set start)

                //  *** End programmer edit section *** (Computer.Owner Set start)
                this.fOwner = value;
                //  *** Start programmer edit section *** (Computer.Owner Set end)

                //  *** End programmer edit section *** (Computer.Owner Set end)
            }
        }
        
        /// <summary>
        /// Computer.
        /// </summary>
        //  *** Start programmer edit section *** (Computer.Parts CustomAttributes)

        //  *** End programmer edit section *** (Computer.Parts CustomAttributes)
        public virtual IIS.Computers.DetailArrayOfComputerPart Parts
        {
            get
            {
                //  *** Start programmer edit section *** (Computer.Parts Get start)

                //  *** End programmer edit section *** (Computer.Parts Get start)
                if ((this.fParts == null))
                {
                    this.fParts = new IIS.Computers.DetailArrayOfComputerPart(this);
                }
                IIS.Computers.DetailArrayOfComputerPart result = this.fParts;
                //  *** Start programmer edit section *** (Computer.Parts Get end)

                //  *** End programmer edit section *** (Computer.Parts Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Computer.Parts Set start)

                //  *** End programmer edit section *** (Computer.Parts Set start)
                this.fParts = value;
                //  *** Start programmer edit section *** (Computer.Parts Set end)

                //  *** End programmer edit section *** (Computer.Parts Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ComputerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ComputerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ComputerE", typeof(IIS.Computers.Computer));
                }
            }
            
            /// <summary>
            /// "ComputerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ComputerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ComputerL", typeof(IIS.Computers.Computer));
                }
            }
        }
    }
}
