//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Computers
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Computer part.
    /// </summary>
    //  *** Start programmer edit section *** (ComputerPart CustomAttributes)

    //  *** End programmer edit section *** (ComputerPart CustomAttributes)
    [AutoAltered()]
    [Caption("Computer part")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ComputerPartE", new string[] {
            "Name as \'Name\'",
            "SerialNumber as \'Serial number\'",
            "SizeOrCapacity as \'Size or capacity\'",
            "ComputerPartType as \'Computer part type\'",
            "ComputerPartType.Name as \'Name\'"}, Hidden=new string[] {
            "ComputerPartType.Name"})]
    [MasterViewDefineAttribute("ComputerPartE", "ComputerPartType", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class ComputerPart : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fSerialNumber;
        
        private string fSizeOrCapacity;
        
        private IIS.Computers.ComputerPartType fComputerPartType;
        
        private IIS.Computers.Computer fComputer;
        
        //  *** Start programmer edit section *** (ComputerPart CustomMembers)

        //  *** End programmer edit section *** (ComputerPart CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (ComputerPart.Name CustomAttributes)

        //  *** End programmer edit section *** (ComputerPart.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (ComputerPart.Name Get start)

                //  *** End programmer edit section *** (ComputerPart.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (ComputerPart.Name Get end)

                //  *** End programmer edit section *** (ComputerPart.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ComputerPart.Name Set start)

                //  *** End programmer edit section *** (ComputerPart.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (ComputerPart.Name Set end)

                //  *** End programmer edit section *** (ComputerPart.Name Set end)
            }
        }
        
        /// <summary>
        /// SerialNumber.
        /// </summary>
        //  *** Start programmer edit section *** (ComputerPart.SerialNumber CustomAttributes)

        //  *** End programmer edit section *** (ComputerPart.SerialNumber CustomAttributes)
        [StrLen(255)]
        public virtual string SerialNumber
        {
            get
            {
                //  *** Start programmer edit section *** (ComputerPart.SerialNumber Get start)

                //  *** End programmer edit section *** (ComputerPart.SerialNumber Get start)
                string result = this.fSerialNumber;
                //  *** Start programmer edit section *** (ComputerPart.SerialNumber Get end)

                //  *** End programmer edit section *** (ComputerPart.SerialNumber Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ComputerPart.SerialNumber Set start)

                //  *** End programmer edit section *** (ComputerPart.SerialNumber Set start)
                this.fSerialNumber = value;
                //  *** Start programmer edit section *** (ComputerPart.SerialNumber Set end)

                //  *** End programmer edit section *** (ComputerPart.SerialNumber Set end)
            }
        }
        
        /// <summary>
        /// SizeOrCapacity.
        /// </summary>
        //  *** Start programmer edit section *** (ComputerPart.SizeOrCapacity CustomAttributes)

        //  *** End programmer edit section *** (ComputerPart.SizeOrCapacity CustomAttributes)
        [StrLen(255)]
        public virtual string SizeOrCapacity
        {
            get
            {
                //  *** Start programmer edit section *** (ComputerPart.SizeOrCapacity Get start)

                //  *** End programmer edit section *** (ComputerPart.SizeOrCapacity Get start)
                string result = this.fSizeOrCapacity;
                //  *** Start programmer edit section *** (ComputerPart.SizeOrCapacity Get end)

                //  *** End programmer edit section *** (ComputerPart.SizeOrCapacity Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ComputerPart.SizeOrCapacity Set start)

                //  *** End programmer edit section *** (ComputerPart.SizeOrCapacity Set start)
                this.fSizeOrCapacity = value;
                //  *** Start programmer edit section *** (ComputerPart.SizeOrCapacity Set end)

                //  *** End programmer edit section *** (ComputerPart.SizeOrCapacity Set end)
            }
        }
        
        /// <summary>
        /// Computer part.
        /// </summary>
        //  *** Start programmer edit section *** (ComputerPart.ComputerPartType CustomAttributes)

        //  *** End programmer edit section *** (ComputerPart.ComputerPartType CustomAttributes)
        [NotNull()]
        public virtual IIS.Computers.ComputerPartType ComputerPartType
        {
            get
            {
                //  *** Start programmer edit section *** (ComputerPart.ComputerPartType Get start)

                //  *** End programmer edit section *** (ComputerPart.ComputerPartType Get start)
                IIS.Computers.ComputerPartType result = this.fComputerPartType;
                //  *** Start programmer edit section *** (ComputerPart.ComputerPartType Get end)

                //  *** End programmer edit section *** (ComputerPart.ComputerPartType Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ComputerPart.ComputerPartType Set start)

                //  *** End programmer edit section *** (ComputerPart.ComputerPartType Set start)
                this.fComputerPartType = value;
                //  *** Start programmer edit section *** (ComputerPart.ComputerPartType Set end)

                //  *** End programmer edit section *** (ComputerPart.ComputerPartType Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Computers.Computer.
        /// </summary>
        //  *** Start programmer edit section *** (ComputerPart.Computer CustomAttributes)

        //  *** End programmer edit section *** (ComputerPart.Computer CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Computers.Computer Computer
        {
            get
            {
                //  *** Start programmer edit section *** (ComputerPart.Computer Get start)

                //  *** End programmer edit section *** (ComputerPart.Computer Get start)
                IIS.Computers.Computer result = this.fComputer;
                //  *** Start programmer edit section *** (ComputerPart.Computer Get end)

                //  *** End programmer edit section *** (ComputerPart.Computer Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ComputerPart.Computer Set start)

                //  *** End programmer edit section *** (ComputerPart.Computer Set start)
                this.fComputer = value;
                //  *** Start programmer edit section *** (ComputerPart.Computer Set end)

                //  *** End programmer edit section *** (ComputerPart.Computer Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ComputerPartE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ComputerPartE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ComputerPartE", typeof(IIS.Computers.ComputerPart));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ComputerPart.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfComputerPart CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfComputerPart CustomAttributes)
    public class DetailArrayOfComputerPart : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Computers.DetailArrayOfComputerPart members)

        //  *** End programmer edit section *** (IIS.Computers.DetailArrayOfComputerPart members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ComputerPart by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ComputerPart.
        /// </summary>
        public DetailArrayOfComputerPart(IIS.Computers.Computer fComputer) : 
                base(typeof(ComputerPart), ((ICSSoft.STORMNET.DataObject)(fComputer)))
        {
        }
        
        public IIS.Computers.ComputerPart this[int index]
        {
            get
            {
                return ((IIS.Computers.ComputerPart)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Computers.ComputerPart dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
