//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Computers
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Office.
    /// </summary>
    //  *** Start programmer edit section *** (Office CustomAttributes)

    //  *** End programmer edit section *** (Office CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("OfficeE", new string[] {
            "Address as \'Address\'",
            "Floor as \'Floor\'"})]
    [View("OfficeL", new string[] {
            "Address as \'Address\'",
            "Floor as \'Floor\'"})]
    public class Office : ICSSoft.STORMNET.DataObject
    {
        
        private string fAddress;
        
        private int fFloor;
        
        //  *** Start programmer edit section *** (Office CustomMembers)

        //  *** End programmer edit section *** (Office CustomMembers)

        
        /// <summary>
        /// Address.
        /// </summary>
        //  *** Start programmer edit section *** (Office.Address CustomAttributes)

        //  *** End programmer edit section *** (Office.Address CustomAttributes)
        [StrLen(255)]
        public virtual string Address
        {
            get
            {
                //  *** Start programmer edit section *** (Office.Address Get start)

                //  *** End programmer edit section *** (Office.Address Get start)
                string result = this.fAddress;
                //  *** Start programmer edit section *** (Office.Address Get end)

                //  *** End programmer edit section *** (Office.Address Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Office.Address Set start)

                //  *** End programmer edit section *** (Office.Address Set start)
                this.fAddress = value;
                //  *** Start programmer edit section *** (Office.Address Set end)

                //  *** End programmer edit section *** (Office.Address Set end)
            }
        }
        
        /// <summary>
        /// Floor.
        /// </summary>
        //  *** Start programmer edit section *** (Office.Floor CustomAttributes)

        //  *** End programmer edit section *** (Office.Floor CustomAttributes)
        public virtual int Floor
        {
            get
            {
                //  *** Start programmer edit section *** (Office.Floor Get start)

                //  *** End programmer edit section *** (Office.Floor Get start)
                int result = this.fFloor;
                //  *** Start programmer edit section *** (Office.Floor Get end)

                //  *** End programmer edit section *** (Office.Floor Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Office.Floor Set start)

                //  *** End programmer edit section *** (Office.Floor Set start)
                this.fFloor = value;
                //  *** Start programmer edit section *** (Office.Floor Set end)

                //  *** End programmer edit section *** (Office.Floor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "OfficeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OfficeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OfficeE", typeof(IIS.Computers.Office));
                }
            }
            
            /// <summary>
            /// "OfficeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OfficeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OfficeL", typeof(IIS.Computers.Office));
                }
            }
        }
    }
}
